[build-system]
requires = [
        "setuptools>=40.8.0",
    "wheel",
    "scikit-build",
    "ninja",
    "scipy", 
    #"tbb-devel",
    "cmake>=3.10.2",
    "networkx",
    "qiskit"
]
build-backend = "setuptools.build_meta"




